name: Release
run-name: "Release"
on:
  workflow_dispatch:
    inputs:
      increment-type:
        description: 'Version increment type'
        required: true
        default: 'patch'
        type: 'choice'
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.pat_github }}
        ref: main
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Update package
      id: update_package
      run: |
        npm ci
        git config --global user.email "yog27ray@example.com"
        git config --global user.name "Yogendra Singh"
        VERSION=$(npm version ${{ github.event.inputs.increment-type }})
        npm run build
        cd dist
        npm publish --access=public
        cd ..
        git push
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
#    - name: Setup Node Github Package
#      uses: actions/setup-node@v4
#      with:
#        node-version: '20.x'
#        registry-url: 'https://npm.pkg.github.com/'
#    - name: Set env
#      run: echo "TAG_NAME=$(cat package.json| jq -r .version)" >> $GITHUB_OUTPUT
#      id: version
#    - name: Create Release
#      id: create_release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.pat_github}}
#      with:
#        tag_name: ${{ steps.version.outputs.TAG_NAME }}
#        release_name: Release ${{ steps.version.outputs.TAG_NAME }}
#        body: |
#          Release v-${{ steps.version.outputs.TAG_NAME }}
#        draft: false
#        prerelease: false
#    - name: Create Github package
#      id: create_github_package
#      run: |
#        ls -lah
#        npm publish --access=public --registry=https://npm.pkg.github.com/
#      env:
#        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
